apiVersion: v1
kind: Secret
metadata:
  name: upi-os-secret
  namespace: default
type: Opaque
stringData:
  # Laravel App Configuration
  APP_NAME: "UPI Core"
  APP_ENV: "production"
  APP_KEY: "base64:IbqfIC1MvCNvkaFpbxIjM20PFL+4Nezp+FZI34Um4k="
  APP_DEBUG: "false"
  APP_URL: "http://upi.local"

  # Database Configuration (MySQL)
  DB_CONNECTION: "mysql"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "upi"
  DB_USERNAME: "laravel"
  DB_PASSWORD: "laravel123"
  DB_ROOT_PASSWORD: "rootpass"

  # Cache / Queue (Redis)
  CACHE_DRIVER: "database"
  QUEUE_CONNECTION: "database"
  REDIS_HOST: "database"
  REDIS_PORT: ""

  # Logging
  LOG_CHANNEL: "stack"
